### ISSUE TITLE
Create an ansible task for downloading icu

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#268]
This should be run for all release machines.

refs: https://github.com/nodejs/build/issues/190

**Comment by joaocgreis** [comment]
This is already included for the Windows machines: https://github.com/janeasystems/build/blob/aded718cdd1b826d0dfe508cc47b8d20a09df58e/setup/windows/ansible-playbook.yaml#L69-L88

**Comment by jbergstroem** [comment]
Here's a slightly improved version I have as part of my "ansible 2.0 refactor":
```yaml
---
# Downloads ICU and verifies checksums
# @requires dest=/tmp

- name: Download ICU
  get_url:
    - url: http://download.icu-project.org/files/icu4c/{{ item.version }}/icu4c-{{ item.version|replace('.','_') }}-src.tgz dest={{ dest }}
    - checksum: md5:{{ item.md5 }}
  with_items:
    - { version: '54.1', md5: 'e844caed8f2ca24c088505b0d6271bc0' }
    - { version: '55.1', md5: 'e2d523df79d6cb7855c2fbe284f4db29' }
    - { version: '56.1', md5: 'c4a2d71ff56aec5ebfab2a3f059be99d' }
```
