### ISSUE TITLE
osx11 release build fails quite often

### ISSUE THREAD

**Issue by targos** [nodejs/build#3006]
Example: https://ci-release.nodejs.org/job/iojs+release/8645/nodes=osx11-release-tar/console

```
15:10:49 make[2]: /bin/sh: Bad address
15:10:52 make[2]: *** [/Users/iojs/build/ws/out/Release/obj.target/v8_base_without_compiler/deps/v8/src/heap/paged-spaces.o] Error 1
15:10:52 make[2]: *** Waiting for unfinished jobs....
```

**Comment by targos** [comment]
3 rebuilds were necessary to make it green:
<img width="225" alt="image" src="https://user-images.githubusercontent.com/2352663/182484970-92babe79-7df3-4345-b7cf-74f50d3d76b7.png">

**Comment by targos** [comment]
/cc @nodejs/build-infra

![image](https://user-images.githubusercontent.com/2352663/183476209-5d405735-c93d-46a3-b52c-f4ce7b75abd3.png)

**Comment by richardlau** [comment]
I have no idea where to even begin with this.

**Comment by targos** [comment]
@AshCripps ?

**Comment by mhdawson** [comment]
I wonder if we are running out of memory.  Does the failure occur more often on any particular machine/type of machine?

**Comment by mhdawson** [comment]
hmm, I guess it's just the one release machine.

**Comment by mhdawson** [comment]
Seems like we actually have two. From history it appears it fails on the macstadium machines and is fine on the nearform one.

I see from the inventory:https://github.com/nodejs/build/blob/main/ansible/inventory.yml

That we have server_jobs set to 6 on the macstadium machines. Maybe that is too many

```
   - macstadium:
        macos11.0-arm64-1:
            ansible_python_interpreter: /usr/bin/python3
            ip: 207.254.38.74
            user: administrator
            remote_env:
                PATH: /opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
            server_jobs: 6
```
