### ISSUE TITLE
set Jenkins CI page header background to default Jenkins color

### ISSUE THREAD

**Issue by F3n67u** [nodejs/build#3024]
I found our Jenkins CI page header background is blue after the Jenkins update.
<img width="831" alt="image" src="https://user-images.githubusercontent.com/12343178/187709345-742bc9ea-52ea-4bcc-8a6e-3c61e1f139cd.png">

The blue background color is set through "extra-css" in the Theme section at https://ci.nodejs.org/configure#section122:
```css
/* blue header background */
#page-header, .task-icon-link[href="/"] {
  background-color: blue;
}
```

The blue background is very dazzling, I think it is too bright. 

Could we remove this blue background CSS and make the page header background to default color? below is the default header background(black, #000):

<img width="837" alt="image" src="https://user-images.githubusercontent.com/12343178/187709227-5894d0f3-bcf9-4ddb-8f41-d2749f0b9f4a.png">
