### ISSUE TITLE
Improve Jenkins alerts and reporting

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3088]
I was checking some issues regarding down machines(#3083, #3084...) and I thought that maybe we can implement a little dashboard in Grafana to check the machine status (ping + latencies) maybe SSH connectivity in the future and trigger alerts (if we want).

I created [this POC repo](https://github.com/UlisesGascon/poc-nodejs-machines-ping-dashboard) that parsers the current inventory (excluding localhost IPs, etc..) and generate a local dockerized environment (Telegraf + influxDb + Grafana). It is just a fast raw prototype to illustrate the idea.

I saw in #3084 that we use the same stack, so it won't be very complex to adapt. What do you think? Should we work on it? Are there other alternatives like [Jenkins-status](https://github.com/nodejs/build/tree/main/tools/jenkins-status) that cover this gap currently?

**Comment by UlisesGascon** [comment]
I have reconsidered this issue and, drawing from the Security WG's experience in implementing the [OpenSSF Scorecard Monitor](https://github.com/marketplace/actions/openssf-scorecard-monitor), I believe we can adopt a similar approach.

We can create a Github Action that parses the inventory file, extracts the IPs, and attempts to ping or SSH into the machines (in the future). The output will be stored as a markdown file ([similar to this one](https://github.com/nodejs/security-wg/blob/main/tools/ossf_scorecard/report.md)), making it easy to identify which machines are UP/DOWN. We can even automatically generate new issues ([similar to this one](https://github.com/nodejs/security-wg/issues/885)) when a machine becomes unreachable.

This process can be initiated on demand and/or scheduled as a daily CRON job.

**Comment by UlisesGascon** [comment]
I created this Github Action [Jenkins status alerts and reporting](https://github.com/marketplace/actions/jenkins-status-alerts-and-reporting) in the marketplace based on my last message idea.

I still need to do some work to fine tune details like unit testing, but in general is already stable and we can use it.

**What this Action can do for us?**

1. This action will store a simple database file ([Here is an example](https://github.com/UlisesGascon/jenkins-status-alerts-and-reporting-demo/blob/main/experimental/database.json)).
2. The github action will compare the stored database with the last state in Jenkins and will create a new issue per machine that was previously online and currently offline (It will ignore the machines that we manually disable in Jenkins). The issues can be tagged and asigned to specific users ([Here is an example](https://github.com/UlisesGascon/jenkins-status-alerts-and-reporting-demo/issues/3))


Additional features:
- It can generate a markdown report that  summarize the Jenkins Nodes status ([Here is an example](https://github.com/UlisesGascon/jenkins-status-alerts-and-reporting-demo/blob/main/experimental/jenkins-report.md))

**Setup proposal**

I will need to create a new github action pipeline in `.github/workflows` with this setup:

```yml
name: "Jenkins Nodes"
on: 
  workflow_dispatch:   

permissions:
  contents: write
  pull-requests: none 
  issues: write
  packages: none

jobs:
  security-scoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Jenkins Alert and Reporting
        uses: UlisesGascon/jenkins-status-alerts-and-reporting@feat/initial-setup
        id: jenkins-status-alerts-and-reporting
        with:
          database: experimental/database.json
          jenkins-domain: 'ci.nodejs.org'
          jenkins-username: ${{ secrets.JENKINS_USERNAME }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          # Issues
          generate-issue: true
          issue-assignees: 'UlisesGascon'
          issue-labels: 'incident,infra'
          create-issues-for-new-offline-nodes: false
          # Report
          report: experimental/jenkins-report.md
          report-tags-enabled: true
          # Git changes
          auto-commit: true
          auto-push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

This setup will require to generate a [Jekins API token](https://www.baeldung.com/ops/jenkins-api-token#:~:text=Click%20on%20%E2%80%9CManage%20Jenkins%E2%80%9D%20in,of%20the%20user%20configuration%20page) and include it in the repo settings (`JENKINS_USERNAME ` and `JENKINS_TOKEN `)

**Next steps**

I will love to try the tool in the Build team and collect feedback to improve the Github Action for the next release as we did for [OpenSSF Scorecard Monitor](https://github.com/UlisesGascon/openssf-scorecard-monitor) in the Security WG when we adopted the tool (https://github.com/nodejs/security-wg/pull/886)

There is an opportunity also to evolve the tool to create tickets when nodes disk usage is high, to give us time to fix them before they go offline.

What do think @nodejs/build ? Should we try it? Do we want to wait to discuss it in the next meeting?
