### ISSUE TITLE
Investigate increasing open file limit

### ISSUE THREAD

**Issue by MattIPv4** [nodejs/build#3259]
A follow-on from https://github.com/nodejs/nodejs.org/issues/5184 and https://github.com/nodejs/nodejs.org/issues/5149, we should look at increasing the number of files that NGINX can have open at any one time.

This could either be done by increasing the system ulimit, or by setting `worker_rlimit_nofile` in NGINX.

**Comment by targos** [comment]
> or by setting `worker_rlimit_nofile` in NGINX.

Are we allowed to do that without increasing the system limit?

**Comment by blimmer** [comment]
We're starting to see a lot more errors that look like this today, which I think is related.

> HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR

I found this ticket from https://github.com/nodejs/nodejs.org/issues/5184

**Comment by MattIPv4** [comment]
> Are we allowed to do that without increasing the system limit?

I've been testing this locally with NGINX in Docker Compose...

<details>
<summary>Soft limit set low, no NGINX limit: errors ❌</summary>

`docker-compose.yml`:

```yaml
  ulimits:
    nofile:
      soft: 50
      hard: 2048
```

`nginx.conf`:

```
# worker_rlimit_nofile 65535;
```

Getting back errors:

```
ab -n 100 -c 50 -v 2 localhost/en/blog.html | grep "Non-2xx"

Non-2xx responses:      2
```
</details>

<details>
<summary>Soft limit set low, NGINX limit set high: errors ❌</summary>

`docker-compose.yml`:

```yaml
  ulimits:
    nofile:
      soft: 50
      hard: 2048
```

`nginx.conf`:

```
worker_rlimit_nofile 65535;
```

Getting back errors:

```
ab -n 100 -c 50 -v 2 localhost/en/blog.html | grep "Non-2xx"

Non-2xx responses:      2
```
</details>

<details>
<summary>Soft limit set high, no NGINX limit set: works ✅</summary>

`docker-compose.yml`:

```yaml
  ulimits:
    nofile:
      soft: 200
      hard: 2048
```

`nginx.conf`:

```
# worker_rlimit_nofile 65535;
```

No errors:

```
ab -n 100 -c 50 -v 2 localhost/en/blog.html | grep "Non-2xx"

[no output]
```
</details>

<details>
<summary>Soft limit set high, NGINX limit set high: works ✅</summary>

`docker-compose.yml`:

```yaml
  ulimits:
    nofile:
      soft: 200
      hard: 2048
```

`nginx.conf`:

```
worker_rlimit_nofile 65535;
```

No errors:

```
ab -n 100 -c 50 -v 2 localhost/en/blog.html | grep "Non-2xx"

[no output]
```
</details>

<details>
<summary>Soft limit set high, NGINX limit set low: errors ❌</summary>

`docker-compose.yml`:

```yaml
  ulimits:
    nofile:
      soft: 200
      hard: 2048
```

`nginx.conf`:

```
worker_rlimit_nofile 50;
```

Getting back errors:

```
ab -n 100 -c 50 -v 2 localhost/en/blog.html | grep "Non-2xx"

Non-2xx responses:      2
```
</details>

So, it would seem that we would need to bump the system soft limit for it to have an impact on NGINX?
